name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # 毎週月曜日の午前9時（UTC）に実行
    - cron: '0 9 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Unit Tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Run Lint
      run: ./gradlew lint --stacktrace
      continue-on-error: true
      
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 14
        
    - name: Upload Lint Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lint-reports
        path: app/build/reports/lint-results*.html
        retention-days: 14
        
    - name: Comment Test Results on PR
      uses: mikepenz/action-junit-report@v4
      if: github.event_name == 'pull_request'
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        check_name: Unit Test Results
        include_passed: true
        detailed_summary: true

